version 3.0

diff --git a/tools/lynis/include/parameters b/tools/lynis/include/parameters
--- a/tools/lynis/include/parameters
+++ b/tools/lynis/include/parameters
@@ -6,7 +6,7 @@
 # ------------------
 #
 # Copyright 2007-2013, Michael Boelen
-# Copyright 2007-2017, CISOfy
+# Copyright 2007-2018, CISOfy
 #
 # Website  : https://cisofy.com
 # Blog     : http://linux-audit.com
@@ -279,27 +279,37 @@
 
             # Define a custom profile file
             --profile)
-                shift
-                SEARCH_PROFILES=$1
+                if [ $# -gt 1 ]; then
+                    shift
+                    SEARCH_PROFILES=$1
+                else
+                    echo "Specify the profile (lynis audit system --profile /home/michael/myprofile.prf)"
+                    exit 1
+                fi
             ;;
 
             # Define a custom plugin directory
             --plugindir | --plugin-dir | --plugins-dir)
-                shift
-                PLUGINDIR=$1
-                LASTCHAR=$(echo $1 | awk '{ print substr($0, length($0))}')
-                if [ "${LASTCHAR}" = "/" ]; then
-                    echo "${RED}Error:${WHITE} plugin directory path should not end with a slash${NORMAL}"
-                    ExitCustom 65
-                fi
-                if [ ! -d ${PLUGINDIR} ]; then
-                    echo "${RED}Error:${WHITE} invalid plugin directory ${PLUGINDIR}${NORMAL}"
-                    ExitCustom 66
+                if [ $# -gt 1 ]; then
+                    shift
+                    PLUGINDIR=$1
+                    LASTCHAR=$(echo $1 | awk '{ print substr($0, length($0))}')
+                    if [ "${LASTCHAR}" = "/" ]; then
+                        echo "${RED}Error:${WHITE} plugin directory path should not end with a slash${NORMAL}"
+                        ExitCustom 65
+                    fi
+                    if [ ! -d ${PLUGINDIR} ]; then
+                        echo "${RED}Error:${WHITE} invalid plugin directory ${PLUGINDIR}${NORMAL}"
+                        ExitCustom 66
+                    fi
+                else
+                    echo "Specify the plugin directory (lynis audit system --plugindir /home/michael/plugins)"
+                    exit 1
                 fi
             ;;
 
             # Quiet mode
-            --quiet | -q)
+            --quiet | -q | --silent)
                 QUIET=1
                 QUICKMODE=1 # Run non-interactive
             ;;
@@ -344,7 +354,7 @@
             ;;
 
             # Skip execution of plugins
-            --skip-plugins | --no-plugins)
+            --skip-plugins | --no-plugins | --noplugins)
                 SKIP_PLUGINS=1
             ;;
 
diff --git a/tools/lynis/include/tests_ports_packages b/tools/lynis/include/tests_ports_packages
--- a/tools/lynis/include/tests_ports_packages
+++ b/tools/lynis/include/tests_ports_packages
@@ -6,7 +6,7 @@
 # ------------------
 #
 # Copyright 2007-2013, Michael Boelen
-# Copyright 2007-2017, CISOfy
+# Copyright 2007-2018, CISOfy
 #
 # Website  : https://cisofy.com
 # Blog     : http://linux-audit.com
@@ -275,6 +275,22 @@
         done
         LogText "Result: found ${COUNT} repositories"
     fi
+#
+#################################################################################
+#
+    # TODO
+
+    ## Test        : PKGS-7318
+    ## Description : APT configuration
+    #if [ -x ${ROOTDIR}usr/bin/apt-config ]; then PREQS_MET="YES"; else PREQS_MET="NO"; fi
+    #Register --test-no PKGS-7318 --preqs-met ${PREQS_MET} --weight L --network NO --category security --description "APT configuration"
+    #if [ ${SKIPTEST} -eq 0 ]; then
+    #    LogText "Test: check APT configuration"
+    #    if ! SkipAtomicTest ${TEST_NO}:atomicname; then
+    #    # Acquire::AllowInsecureRepositories should be 0 (could be 1)
+    #    # Acquire::AllowDowngradeToInsecureRepositories should be 0
+    #    # Binary::apt::Acquire::AllowInsecureRepositories should be 0
+    #fi
 #
 #################################################################################
 #
@@ -617,7 +633,7 @@
     # Test        : PKGS-7370
     # Description : Checking debsums installation status and presence in cron job
     # Note        : Run this only when it is a DPKG based system
-    if [ ! -z "${DPKGBINARY}" -a "${LINUX_VERSION}" = "Debian" ]; then PREQS_MET="YES"; else PREQS_MET="NO"; fi
+    if [ ! -z "${DPKGBINARY}" ]; then PREQS_MET="YES"; else PREQS_MET="NO"; fi
     Register --test-no "PKGS-7370" --preqs-met ${PREQS_MET} --weight L --network NO --category security --description "Checking for debsums utility"
     if [ ${SKIPTEST} -eq 0 ]; then
         if [ ! -z "${DEBSUMSBINARY}" ]; then
@@ -677,7 +693,7 @@
         if [ -x ${ROOTDIR}usr/sbin/pkg_admin ]; then
             PACKAGE_AUDIT_TOOL_FOUND=1
             PACKAGE_AUDIT_TOOL="pkg_admin audit"
-            if [ -f ${ROOTDIR}var/db/pkg/pkgs-vulnerabilities ]; then
+            if [ -f ${ROOTDIR}var/db/pkg/pkg-vulnerabilities ]; then
                 FIND=$(${ROOTDIR}usr/sbin/pkg_admin audit)
                 if [ -z "${FIND}" ]; then
                     LogText "Result: pkg_admin audit results are clean"
@@ -810,11 +826,12 @@
     if [ ! -z "${YUMBINARY}" -a -z "${DNFBINARY}" ]; then PREQS_MET="YES"; else PREQS_MET="NO"; fi
     Register --test-no PKGS-7384 --preqs-met ${PREQS_MET} --os Linux --weight L --network NO --category security --description "Check for YUM utils package"
     if [ ${SKIPTEST} -eq 0 ]; then
-        if [ -x ${ROOTDIR}usr/bin/package-cleanup ]; then
-            LogText "Result: found YUM utils package (${ROOTDIR}usr/bin/package-cleanup)"
+        # package-cleanup tool can be found in different locations
+        if [ -x ${ROOTDIR}bin/package-cleanup -o -x ${ROOTDIR}usr/bin/package-cleanup ]; then
+            LogText "Result: found YUM utils package (package-cleanup)"
             # Check for duplicates
             LogText "Test: Checking for duplicate packages"
-            FIND=$(${ROOTDIR}usr/bin/package-cleanup -q --dupes > /dev/null; echo $?)
+            FIND=$(package-cleanup -q --dupes > /dev/null; echo $?)
             if [ "${FIND}" = "0" ]; then
                 LogText "Result: No duplicate packages found"
                 Display --indent 2 --text "- Checking package database duplicates" --result "${STATUS_OK}" --color GREEN
@@ -827,7 +844,7 @@
 
             # Check for package database problems
             LogText "Test: Checking for database problems"
-            FIND=$(${ROOTDIR}usr/bin/package-cleanup --problems > /dev/null; echo $?)
+            FIND=$(package-cleanup --problems > /dev/null; echo $?)
             if [ "${FIND}" = "0" ]; then
                 LogText "Result: No package database problems found"
                 Display --indent 2 --text "- Checking package database for problems" --result "${STATUS_OK}" --color GREEN
@@ -931,7 +948,7 @@
     if [ ${SKIPTEST} -eq 0 ]; then
         if [ ! -z "${PYTHONBINARY}" ]; then
             LogText "Test: checking enabled repositories"
-            REPOS=$(${PYTHONBINARY} -c 'import yum ; yb = yum.YumBase() ; print [(r.id + "=" + str(r.gpgcheck)) for r in yb.repos.listEnabled()]' | ${GREPBINARY} "^\[" | ${TRBINARY} -d '[] ' | ${TRBINARY} -d "'" | ${SEDBINARY} 's/,/ /g')
+            REPOS=$(${PYTHONBINARY} -c 'import yum ; yb = yum.YumBase() ; yb.conf ; print [(r.id + "=" + str(r.gpgcheck)) for r in yb.repos.listEnabled()]' | ${GREPBINARY} "^\[" | ${TRBINARY} -d '[] ' | ${TRBINARY} -d "'" | ${SEDBINARY} 's/,/ /g')
             if [ -z "${REPOS}" ]; then LogText "Result: found no repositories"; fi
             for I in ${REPOS}; do
                 REPO=$(echo ${I} | ${AWKBINARY} -F= '{print $1}')
diff --git a/tools/lynis/lynis b/tools/lynis/lynis
--- a/tools/lynis/lynis
+++ b/tools/lynis/lynis
@@ -35,15 +35,15 @@
     PROGRAM_AUTHOR_CONTACT="lynis-dev@cisofy.com"
 
     # Version details
-    PROGRAM_RELEASE_DATE="2017-07-11"
-    PROGRAM_RELEASE_TIMESTAMP=1499694342
+    PROGRAM_RELEASE_DATE="2018-07-25"
+    PROGRAM_RELEASE_TIMESTAMP=1530882211
     PROGRAM_RELEASE_TYPE="dev" # dev or final
-    PROGRAM_VERSION="2.5.3"
+    PROGRAM_VERSION="2.6.7"
 
     # Source, documentation and license
     PROGRAM_SOURCE="https://github.com/CISOfy/lynis"
     PROGRAM_WEBSITE="https://cisofy.com/lynis/"
-    PROGRAM_COPYRIGHT="2007-2017, ${PROGRAM_AUTHOR} - ${PROGRAM_WEBSITE}"
+    PROGRAM_COPYRIGHT="2007-2018, ${PROGRAM_AUTHOR} - ${PROGRAM_WEBSITE}"
     PROGRAM_LICENSE="${PROGRAM_NAME} comes with ABSOLUTELY NO WARRANTY. This is free software, and you are
   welcome to redistribute it under the terms of the GNU General Public License.
   See the LICENSE file for details about using this software."
@@ -130,7 +130,7 @@ Make sure to execute ${PROGRAM_NAME} from untarred directory or check your insta
     else
         MYID=$(id -u 2> /dev/null)
     fi
-    if [ -z "${MYID}" ]; then Display "Could not find user ID with id command. Want to help improving Lynis? Raise a ticket at ${PROGRAM_SOURCE}"; ExitFatal; fi
+    if [ -z "${MYID}" ]; then Display "Could not find user ID with id command. Want to help improve Lynis? Raise a ticket at ${PROGRAM_SOURCE}"; ExitFatal; fi
 #
 #################################################################################
 #
@@ -238,15 +238,21 @@ Make sure to execute ${PROGRAM_NAME} from untarred directory or check your insta
         if [ -z "${LOGFILE}" ]; then
             # Try creating a log file in temporary directory
             if [ ! -f /tmp/lynis.log ]; then
+                if [ -L /tmp/lynis.log ]; then echo "Log file is symlinked, which can introduce the risk of a symlink attack."; exit 1; fi
                 touch /tmp/lynis.log
                 if [ $? -eq 0 ]; then LOGFILE="/tmp/lynis.log"; else LOGFILE="/dev/null"; fi
             else
                 LOGFILE="/tmp/lynis.log"
             fi
+        else
+            if [ -L "${LOGFILE}" ]; then echo "Log file is symlinked, which can introduce the risk of a symlink attack."; exit 1; fi
         fi
         if [ -z "${REPORTFILE}" ]; then
             touch /tmp/lynis-report.dat
+            if [ -L /tmp/lynis-report.dat ]; then echo "Report file is symlinked, which can introduce the risk of a symlink attack."; exit 1; fi
             if [ $? -eq 0 ]; then REPORTFILE="/tmp/lynis-report.dat"; else REPORTFILE="/dev/null"; fi
+        else
+            if [ -L "${REPORTFILE}" ]; then echo "Report file is symlinked, which can introduce the risk of a symlink attack."; exit 1; fi
         fi
     fi
 #
@@ -297,9 +303,10 @@ ${NORMAL}
     DiscoverProfiles
 
     # Initialize and check profile file, auditor name, log file and report file
+    if [ -z "${LOGDIR}" ];            then LOGDIR="/var/log"; fi
     if [ -z "${AUDITORNAME}" ];       then AUDITORNAME="[Not Specified]"; fi
-    if [ -z "${LOGFILE}" ];           then LOGFILE="/var/log/lynis.log"; fi
-    if [ -z "${REPORTFILE}" ];        then REPORTFILE="/var/log/lynis-report.dat"; fi
+    if [ -z "${LOGFILE}" ];           then LOGFILE="${LOGDIR}/lynis.log"; fi
+    if [ -z "${REPORTFILE}" ];        then REPORTFILE="${LOGDIR}/lynis-report.dat"; fi
 #
 #################################################################################
 #
@@ -326,9 +333,9 @@ ${NORMAL}
 
 ${WARNING}Warning${NORMAL}: ${WHITE}PID file exists, probably another Lynis process is running.${NORMAL}
 ------------------------------------------------------------------------------
-If you are unsure another Lynis process is running currently, you are advised
-to stop current process and check the process list first. If you cancelled
-(by using CTRL+C) a previous instance, you can ignore this message.
+If you are unsure if another Lynis process is running currently, you are advised
+to stop the current process and check the process list first. If you cancelled
+a previous instance (by using CTRL+C), you can ignore this message.
 
 You are advised to check for temporary files after program completion.
 ------------------------------------------------------------------------------
@@ -341,7 +348,7 @@ ${YELLOW}Note: ${WHITE}Cancelling the program can leave temporary files behind${
             echo "Quitting, to prevent multiple cron jobs running at the same time"
             exit 1 # Manually exit, no cleanups to prevent deleting an active PID file
         else
-            wait_for_keypress
+            WaitForKeyPress
         fi
 
         # Deleting any stale PID files that might exist. Note: Display function does not work yet at this point
@@ -388,7 +395,6 @@ ${YELLOW}Note: ${WHITE}Cancelling the program can leave temporary files behind${
 
     ${CYAN}update${NORMAL}
         update info                   : Show update details
-        update release                : Update Lynis release
 
 
   ${WHITE}Options:${NORMAL}
@@ -410,7 +416,7 @@ ${YELLOW}Note: ${WHITE}Cancelling the program can leave temporary files behind${
     ${GRAY}--version (-V)${NORMAL}                    : Display version number and quit
 
     ${WHITE}Enterprise options${NORMAL}
-    ${GRAY}--plugin-dir ${BROWN}\"<path>\"${NORMAL}             : Define path of available plugins
+    ${GRAY}--plugindir ${BROWN}<path>${NORMAL}                : Define path of available plugins
     ${GRAY}--upload${NORMAL}                          : Upload data to central node
 
     More options available. Run '$0 show options', or use the man page.
@@ -434,7 +440,7 @@ ${YELLOW}Note: ${WHITE}Cancelling the program can leave temporary files behind${
 #
 #################################################################################
 #
-    if [ ${PRIVILEGED} -eq 0 -a ${CHECK} -eq 1 ]; then
+    if [ ${PRIVILEGED} -eq 0 -a ${CHECK} -eq 1 -a ${QUIET} -eq 0 ]; then
         printf "%s" "${WHITE}
   ###################################################################
   #                                                                 #
@@ -454,8 +460,6 @@ ${NORMAL}
   ${RED}WARNING:${NORMAL}
   ${WHITE}*${NORMAL} No suggestions or warnings will be displayed in report (due to missing log file)"
         fi
-        #printf "\n\n%s" "  ${WHITE}Press [ENTER] to continue or [CTRL] + C to break${NORMAL}"
-        #if [ ${QUICKMODE} -eq 0 ]; then read void; fi
     fi
 #
 #################################################################################
@@ -551,7 +555,7 @@ ${NORMAL}
         Display --indent 2 --text "- Detecting language and localization" --result "${LANGUAGE}" --color WHITE
         if [ ! -f ${DBDIR}/languages/${LANGUAGE} ]; then
             Display --indent 4 --text "${YELLOW}Notice:${NORMAL} no language file found for '${LANGUAGE}' (tried: ${DBDIR}/languages/${LANGUAGE})"
-            if IsDeveloperVersion; then Display --indent 4 --text "See https://github.com/CISOfy/lynis-sdk/documentation/10-translations.md for more details to help translating Lynis"; fi
+            if IsDeveloperVersion; then Display --indent 4 --text "See https://github.com/CISOfy/lynis-sdk/documentation/10-translations.md for more details to help translate Lynis"; fi
             sleep 5
         else
             LogText "Importing language file (${DBDIR}/languages/${LANGUAGE})"
@@ -617,6 +621,7 @@ ${NORMAL}
         echo "  Plugin directory:          ${PLUGINDIR}"
         echo "  ---------------------------------------------------"
         echo "  Auditor:                   ${AUDITORNAME}"
+        echo "  Language:                  ${LANGUAGE}"
         echo "  Test category:             ${TEST_CATEGORY_TO_CHECK}"
         echo "  Test group:                ${TEST_GROUP_TO_CHECK}"
         if [ ! "${ROOTDIR}" = "/" ]; then echo "  Root directory (custom):   ${ROOTDIR}"; fi
@@ -727,8 +732,8 @@ ${NORMAL}
         OLD_RELEASE=1
     fi
 
-    # Show on screen message if release is very outdated
-    if [ ${UPDATE_AVAILABLE} -eq 1 ]; then
+    # Show on screen message if release is very outdated (unless --quiet/--silent is used)
+    if [ ${UPDATE_AVAILABLE} -eq 1 -a ${QUIET} -eq 0 ]; then
         echo ""
         echo "      ==============================================================================="
         echo "        ${CYAN}${PROGRAM_NAME} ${TEXT_UPDATE_AVAILABLE}${NORMAL}"
@@ -743,12 +748,13 @@ ${NORMAL}
             echo ""
         fi
         echo "        ${WHITE}Please update to the latest version.${NORMAL}"
-        echo "        New releases include additional features, bug fixes, tests and baselines.${NORMAL}"
+        echo "        New releases include additional features, bug fixes, tests, and baselines.${NORMAL}"
         echo ""
         echo "        Download the latest version:"
+        echo ""
         echo "        Packages (DEB/RPM) -  https://packages.cisofy.com"
-        echo "        Website            -  https://cisofy.com/downloads/"
-        echo "        GitHub             -  https://github.com/CISOfy/lynis"
+        echo "        Website (TAR)      -  https://cisofy.com/downloads/"
+        echo "        GitHub (source)    -  https://github.com/CISOfy/lynis"
         echo ""
         echo "      ==============================================================================="
         echo ""
@@ -782,13 +788,14 @@ ${NORMAL}
 #
 #################################################################################
 #
-    # Check for systemd presence
-    if [ -d ${ROOTDIR}lib/systemd/system -a -f ${ROOTDIR}usr/lib/systemd/systemd ]; then
-        LogText "Result: systemd is using systemd"
+    # Check for systemd active
+    if [ -d /run/systemd/system ]; then
+        LogText "Result: system is using systemd"
         HAS_SYSTEMD=1
         Report "systemd=1"
     else
-        LogText "Result: systemd not found, or partially"
+        LogText "Result: systemd not found"
+        HAS_SYSTEMD=0
         Report "systemd=0"
     fi
 #
@@ -900,6 +907,9 @@ ${NORMAL}
     else
         LogText "Info: no HostID found or invalid one"
     fi
+    if [ ! "${HOSTID2}" = "" ]; then
+        Report "hostid2=${HOSTID2}"
+    fi
     if [ ! "${MACHINEID}" = "" ]; then
         LogText "Info: found a machine ID ${MACHINEID}"
         Report "machineid=${MACHINEID}"
@@ -918,7 +928,7 @@ ${NORMAL}
             LogText "Info: perform tests from all categories"
 
             INCLUDE_TESTS="boot_services kernel memory_processes authentication shells \
-                           filesystems storage storage_nfs nameservices ports_packages networking printers_spools \
+                           filesystems usb storage storage_nfs nameservices dns ports_packages networking printers_spools \
                            mail_messaging firewalls webservers ssh snmp databases ldap php squid logging \
                            insecure_services banners scheduling accounting time crypto virtualization containers \
                            mac_frameworks file_integrity tooling malware file_permissions homedirs \
@@ -1065,4 +1075,4 @@ ${NORMAL}
 
 #
 #================================================================================
-# Lynis - Copyright 2007-2017, Michael Boelen, CISOfy - https://cisofy.com
+# Lynis - Copyright 2007-2018, Michael Boelen, CISOfy - https://cisofy.com
